
CREATE TABLE CARS
(
  CARS_ID              VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  YEAR                 INTEGER     NOT NULL COMMENT '연식',
  CARNAME_CODE_ID      VARCHAR(50) NOT NULL COMMENT '유니크ID',
  COMPANY NAME_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (CARS_ID)
) COMMENT '자동차';

CREATE TABLE CARS_ OPTIONS
(
  CARS_ID         VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  CARS_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID'
) COMMENT '자동차 옵션';

CREATE TABLE CARS_NAME 
(
  CARNAME_CODE_ID      VARCHAR(50) NOT NULL COMMENT '유니크ID',
  CARSNAME             VARCHAR(50) NOT NULL COMMENT '자동차이름',
  COMPANY_NAME_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (CARNAME_CODE_ID)
) COMMENT '자동차이름 ';

CREATE TABLE CARS_OPTION CODE
(
  CARS_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  OPTINON_NAME    VARCHAR(50) NOT NULL COMMENT '옵션 종류',
  PRIMARY KEY (CARS_OPTIONS_ID)
) COMMENT '옵션 ';

CREATE TABLE COMPAN_ NAME
(
  COMPANY_NAME_CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  CARS_ID              VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (COMPANY_NAME_CODE_ID)
) COMMENT '회사이름';

ALTER TABLE CARS_ OPTIONS
  ADD CONSTRAINT FK_CARS_TO_CARS_ OPTIONS
    FOREIGN KEY (CARS_ID)
    REFERENCES CARS (CARS_ID);

ALTER TABLE CARS_NAME 
  ADD CONSTRAINT FK_COMPAN_ NAME_TO_CARS_NAME 
    FOREIGN KEY (COMPANY_NAME_CODE_ID)
    REFERENCES COMPAN_ NAME (COMPANY_NAME_CODE_ID);

ALTER TABLE CARS_ OPTIONS
  ADD CONSTRAINT FK_CARS_OPTION CODE_TO_CARS_ OPTIONS
    FOREIGN KEY (CARS_OPTIONS_ID)
    REFERENCES CARS_OPTION CODE (CARS_OPTIONS_ID);

ALTER TABLE CARS
  ADD CONSTRAINT FK_COMPAN_ NAME_TO_CARS
    FOREIGN KEY (COMPANY NAME_CODE_ID)
    REFERENCES COMPAN_ NAME (COMPANY_NAME_CODE_ID);
