-- OPTION_NAME 값 추출 하기 
SELECT T_OPT_INFOR.OPTION_NAME
FROM option_infors AS T_OPT_INFOR
	JOIN `options` AS T_OPTS
    ON T_OPT_INFOR.OPTION_INFOR_ID = T_OPTS.OPTION_INFOR_ID 
    AND T_OPTS.CAR_INFOR_ID = 'CI005'
;

--  'CI001'의 값이 몇개인지 확인하기(검토용) 
SELECT COUNT(*)
FROM `OPTIONS` AS T_OPTS
WHERE T_OPTS.CAR_INFOR_ID = 'CI001'
;