
CREATE TABLE GENDER_CODE
(
  GENDER CODE_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  GENDER         VARCHAR(50) NOT NULL COMMENT '성별',
  PRIMARY KEY (GENDER CODE_ID)
) COMMENT '성별';

CREATE TABLE MEDICALCHECKUP
(
  MEDICALCHECKUP_ID VARCHAR(50)  NOT NULL COMMENT '유니크ID',
  NAME              VARCHAR(50)  NOT NULL COMMENT '이름',
  AGE               INTEGER      NOT NULL COMMENT '나이',
  RESULR CODE_ID    VARCHAR(500) NOT NULL COMMENT '유니크 ID',
  GENDER CODE_ID    VARCHAR(50)  NOT NULL COMMENT '유니크 ID',
  HEIGHT            INTEGER      NOT NULL COMMENT '키',
  WEGIHT            INTEGER      NOT NULL COMMENT '몸무게',
  BLOOD_PRESUURE    INTEGER      NOT NULL COMMENT '혈압',
  BLOOD_SUGAR       INTEGER      NOT NULL COMMENT '혈당',
  PRIMARY KEY (MEDICALCHECKUP_ID)
) COMMENT '메디컬 체크';

CREATE TABLE REMEDICAL_CHECKUP_CODE
(
  REMEDICAL_CHECK_ID VARCHAR(50) NOT NULL COMMENT '유니크 ID',
  REMEDICAL_CHECKUP  VARCHAR(50) NOT NULL COMMENT '재검진항목',
  PRIMARY KEY (REMEDICAL_CHECK_ID)
) COMMENT '재검진 항목';

CREATE TABLE RESULT_CODE
(
  RESULR_CODE_ID     VARCHAR(500) NOT NULL COMMENT '유니크 ID',
  RESULT             VARCHAR(500) NOT NULL COMMENT '결과 ',
  MAINTENANCE        VARCHAR(500) NOT NULL COMMENT '유지 방안',
  REMEDICAL_CHECK_ID VARCHAR(50)  NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (RESULR_CODE_ID)
) COMMENT '검진 결과 ';

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_RESULT_CODE_TO_MEDICALCHECKUP
    FOREIGN KEY (RESULR CODE_ID)
    REFERENCES RESULT_CODE (RESULR_CODE_ID);

ALTER TABLE MEDICALCHECKUP
  ADD CONSTRAINT FK_GENDER_CODE_TO_MEDICALCHECKUP
    FOREIGN KEY (GENDER CODE_ID)
    REFERENCES GENDER_CODE (GENDER CODE_ID);

ALTER TABLE RESULT_CODE
  ADD CONSTRAINT FK_REMEDICAL_CHECKUP_CODE_TO_RESULT_CODE
    FOREIGN KEY (REMEDICAL_CHECK_ID)
    REFERENCES REMEDICAL_CHECKUP_CODE (REMEDICAL_CHECK_ID);
